"""Offline training contracts with accelerator imports kept opt-in."""

from .batches import (
    AllActionTrajectoryBatchV1,
    BUTTON_TARGET_INDICES,
    CONTINUOUS_TARGET_INDICES,
    CONTROL_LAYOUT_ID,
    CONTROL_VECTOR_SIZE,
    MazeChaseBatchConfig,
    MazeChaseBatchSource,
    MixedWorldBatchConfig,
    MixedWorldBatchSource,
    MovingShapesBatchSource,
    SolverBatchConfig,
    SolverBatchSource,
    TrajectoryBatch,
    control_to_vector,
    dataset_batch_source,
)
from .checkpoint import (
    LoadedCheckpoint,
    TrainerCursor,
    file_sha256,
    load_checkpoint,
    save_checkpoint,
    source_tree_sha256,
)
from .config import (
    DatasetConfig,
    DeterminismConfig,
    LoggingConfig,
    OptimizationConfig,
    PrecisionConfig,
    ResourceConfig,
    RunConfig,
    TrainingConfig,
    TrainingStageConfig,
    load_training_config,
)
from .metrics import JsonlMetricWriter, MetricRecord
from .protocol import (
    DeterministicBatchSource,
    StagedTrainingSystem,
    TrainingStepResult,
    TrainingSystem,
)
from .trainer import Trainer, TrainingSummary

__all__ = [
    "AllActionTrajectoryBatchV1",
    "BUTTON_TARGET_INDICES",
    "CONTINUOUS_TARGET_INDICES",
    "CONTROL_LAYOUT_ID",
    "CONTROL_VECTOR_SIZE",
    "DatasetConfig",
    "DeterminismConfig",
    "DeterministicBatchSource",
    "JsonlMetricWriter",
    "LoadedCheckpoint",
    "LoggingConfig",
    "MetricRecord",
    "MazeChaseBatchConfig",
    "MazeChaseBatchSource",
    "MixedWorldBatchConfig",
    "MixedWorldBatchSource",
    "MovingShapesBatchSource",
    "OptimizationConfig",
    "PrecisionConfig",
    "ResourceConfig",
    "RunConfig",
    "SolverBatchConfig",
    "SolverBatchSource",
    "StagedTrainingSystem",
    "Trainer",
    "TrainerCursor",
    "TrainingConfig",
    "TrainingStageConfig",
    "TrainingStepResult",
    "TrainingSummary",
    "TrainingSystem",
    "TrajectoryBatch",
    "control_to_vector",
    "dataset_batch_source",
    "file_sha256",
    "load_checkpoint",
    "load_training_config",
    "save_checkpoint",
    "source_tree_sha256",
]
